import Alpine from 'alpinejs';
import { initPublicSurfaceTheme } from './public-surface-theme';
import { arkRepairOrderMileage } from './ark-repair-order-mileage';
import { initRoFooterCompose } from './ark-ro-footer-compose';
import { arkRepairOrderVisitPosture } from './ark-repair-order-visit-posture';
import {
    arkRepairOrderIdentityCustomer,
    arkRepairOrderIdentityVehicle,
    arkRepairOrderVehicleChange,
} from './ark-repair-order-identity-edit';
import { arkDealerQuoteCapture } from './ark-dealer-quote-capture';
import { arkVehicleDecode } from './ark-vehicle-decode';
import { arkCustomerVehicleRail } from './ark-customer-vehicle-rail';
import { arkCustomerHubTabs } from './ark-customer-hub-tabs';
import { arkWorkSurfaceTabs } from './ark-work-surface-tabs';
import { arkReloadRepairOrderWorkspaceTab, arkRoWorkspaceTabs, arkSelectRepairOrderWorkspaceTab } from './ark-ro-workspace-tabs';
import { arkCustomerHubComms } from './ark-customer-hub-comms';
import { arkIntakeFindCustomer } from './ark-intake-find-customer';
import { arkIntakeOpenRo } from './ark-intake-open-ro';
import { arkIntakeVehicleCheckin } from './ark-intake-vehicle-checkin';
import { arkIntakeVehicleSelect } from './ark-intake-vehicle-select';
import { arkVinDisplay } from './ark-vin-display';
import { arkWorksheetCollaboration } from './ark-worksheet-collaboration';
import { arkWorksheetContinuity, arkWorksheetFormSubmit, initPartProcurementSelect, initRepairOrderLifecycleSelect } from './ark-worksheet-continuity';
import { loadedLaborCostCalculator } from './ark-loaded-labor-cost-calculator';
import { shopOverheadCalculator } from './ark-shop-overhead-calculator';
import { arkOperationalClock } from './ark-operational-clock';
import { arkPortalEstimateDeposit, arkPortalInvoicePay } from './ark-square-payments';
import { arkPortalEstimateForm } from './ark-portal-estimate-authorization';
import { arkPortalSignature } from './ark-portal-signature';
import { initWorkspaceTabs } from './ark-workspace-tabs';
import { initWorkspaceDirtyBindings } from './ark-workspace-dirty-bindings';
import { initRoWorkspaceMemory } from './ark-ro-workspace-memory';
import { initIntakeWorkspaceMemory } from './ark-intake-workspace-memory';
import { arkCommsInterrupt } from './ark-comms-interrupt';
import { initStaffPresenceHeartbeat } from './ark-staff-presence';
import { initWorkstationPresence } from './ark-workstation-presence';
import { arkCallQueue } from './ark-call-queue';
import { arkTelephonyCallback, initiateTelephonyCallback } from './ark-telephony-callback';
import { markCallSessionHandled } from './ark-mark-call-handled';
import { arkConversationQuickReply } from './ark-conversation-quick-reply';
import { arkPortalSendMenu } from './ark-portal-send-menu';
import { arkReviewPrintMenu } from './ark-review-print-menu';
import { arkFloatingCommsMenu } from './ark-floating-comms-menu';
import { arkMessengerLinkCustomer } from './ark-messenger-link-customer';
import { arkLearnPrintSelect } from './ark-learn-print';
import { arkLearnProgress } from './ark-learn-progress';
import { arkLearnVideo } from './ark-learn-video';
import { arkInspectionWalk } from './ark-inspection-walk';
import { arkInspectionSectionWalk } from './ark-inspection-section-walk';
import { initInspectionCaptureSurfaceCtas } from './ark-inspection-capture-surface';
import { arkImageLightbox } from './ark-image-lightbox';
import { arkLearnGuideModal } from './ark-learn-guide-modal';
import { initWorkItemQuickAdd } from './ark-work-quick-add';
import { initWorkRecentActivity } from './ark-work-recent-activity';
import { initCommsWorkboard } from './ark-comms-workboard';
import { initOpsWorkboardTriage } from './ark-ops-workboard-triage';
import { initCommsWorkspace } from './ark-comms-workspace';
import { initCommsNavPressure } from './ark-comms-nav-pressure';
import { initOpsGlobalSearch } from './ark-ops-global-search';
import { initDepositBreakdowns } from './ark-deposit-breakdown';
import { arkRoModeControl, initRoModeControl } from './ark-ro-mode-control';
import { arkWorkspaceModal } from './ark-workspace-modal';
import { arkSavedWorkPicker } from './ark-saved-work-picker';
import { arkDragonServiceAdvisor } from './ark-dragon-service-advisor';
import { arkReviewEstimateNotes } from './ark-review-estimate-notes';
import { arkDocumentAdd } from './ark-document-add';
import { initWorkspaceStrip } from './ark-workspace-strip';
import { arkScopeEntryIntake, focusWorksheetConcernRepairAction } from './ark-scope-entry-intake';
import { arkLaborMemorySuggest } from './ark-labor-memory-suggest';
import { arkRoMention } from './ark-repair-order-mention';
import { arkRteLaborGuide } from './ark-rte-labor-guide';
import { arkPaymentCapture } from './ark-payment-capture';
import { arkInspectPopover } from './ark-inspect-popover';
import { arkAuthorizationExceptionDialog } from './ark-authorization-exception-dialog';
import { initNumericOnlyInputs } from './ark-numeric-only';
window.Alpine = Alpine;
window.arkInitiateTelephonyCallback = initiateTelephonyCallback;
window.arkMarkCallSessionHandled = markCallSessionHandled;
window.arkRteLaborGuide = arkRteLaborGuide;
window.arkScopeEntryIntake = arkScopeEntryIntake;
window.arkLaborMemorySuggest = arkLaborMemorySuggest;
window.arkRoMention = arkRoMention;
window.arkWorksheetCollaboration = arkWorksheetCollaboration;
window.arkWorksheetContinuity = arkWorksheetContinuity;
window.arkWorksheetFormSubmit = arkWorksheetFormSubmit;
window.arkRoWorkspaceTabs = arkRoWorkspaceTabs;
window.arkRoRailTabs = arkRoWorkspaceTabs;
window.arkReloadRepairOrderWorkspaceTab = arkReloadRepairOrderWorkspaceTab;
window.arkSelectRepairOrderWorkspaceTab = arkSelectRepairOrderWorkspaceTab;

Alpine.data('arkRepairOrderMileage', arkRepairOrderMileage);
Alpine.data('arkRepairOrderVisitPosture', arkRepairOrderVisitPosture);
Alpine.data('arkRepairOrderIdentityCustomer', arkRepairOrderIdentityCustomer);
Alpine.data('arkRepairOrderIdentityVehicle', arkRepairOrderIdentityVehicle);
Alpine.data('arkRepairOrderVehicleChange', arkRepairOrderVehicleChange);
Alpine.data('arkDealerQuoteCapture', (config = {}) => arkDealerQuoteCapture(config));
Alpine.data('arkVehicleDecode', (config = {}) => arkVehicleDecode(config));
Alpine.data('arkCustomerVehicleRail', (config = {}) => arkCustomerVehicleRail(config));
Alpine.data('arkCustomerHubTabs', (initialTab = 'vehicles') => arkCustomerHubTabs(initialTab));
Alpine.data('arkWorkSurfaceTabs', (initialTab = 'overview') => arkWorkSurfaceTabs(initialTab));
Alpine.data('arkRoWorkspaceTabs', (config = {}) => arkRoWorkspaceTabs(config));
Alpine.data('arkRoRailTabs', (config = {}) => arkRoWorkspaceTabs(config));
Alpine.data('arkCustomerHubComms', (config = {}) => arkCustomerHubComms(config));
Alpine.data('arkIntakeFindCustomer', (config = {}) => arkIntakeFindCustomer(config));
Alpine.data('arkIntakeOpenRo', (config = {}) => arkIntakeOpenRo(config));
Alpine.data('arkIntakeVehicleCheckin', (config = {}) => arkIntakeVehicleCheckin(config));
Alpine.data('arkIntakeVehicleSelect', (config = {}) => arkIntakeVehicleSelect(config));
Alpine.data('arkVinDisplay', arkVinDisplay);
Alpine.data('loadedLaborCostCalculator', (config = {}) => loadedLaborCostCalculator(config));
Alpine.data('shopOverheadCalculator', (config = {}) => shopOverheadCalculator(config));
Alpine.data('arkPortalInvoicePay', (config = {}) => arkPortalInvoicePay(config));
Alpine.data('arkPortalSignature', (config = {}) => arkPortalSignature(config));
Alpine.data('arkPortalEstimateForm', (config = {}) => arkPortalEstimateForm(config));
Alpine.data('arkPortalEstimateDeposit', (config = {}) => arkPortalEstimateDeposit(config));
Alpine.data('arkCommsInterrupt', arkCommsInterrupt);
Alpine.data('arkCallQueue', () => arkCallQueue());
Alpine.data('arkTelephonyCallback', arkTelephonyCallback);
Alpine.data('arkConversationQuickReply', (config = {}) => arkConversationQuickReply(config));
Alpine.data('arkPaymentCapture', (config = {}) => arkPaymentCapture(config));
Alpine.data('arkPortalSendMenu', (config = {}) => arkPortalSendMenu(config));
Alpine.data('arkReviewPrintMenu', arkReviewPrintMenu);
Alpine.data('arkFloatingCommsMenu', (config = {}) => arkFloatingCommsMenu(config));
Alpine.data('arkMessengerLinkCustomer', (config = {}) => arkMessengerLinkCustomer(config));
Alpine.data('arkLearnPrintSelect', arkLearnPrintSelect);
Alpine.data('arkLearnProgress', (config = {}) => arkLearnProgress(config));
Alpine.data('arkLearnVideo', (config = {}) => arkLearnVideo(config));
Alpine.data('arkInspectionWalk', (config = {}) => arkInspectionWalk(config));
Alpine.data('arkInspectionSectionWalk', (config = {}) => arkInspectionSectionWalk(config));
Alpine.data('arkInspectPopover', arkInspectPopover);
Alpine.data('arkAuthorizationExceptionDialog', (config = {}) => arkAuthorizationExceptionDialog(config));
Alpine.data('arkImageLightbox', arkImageLightbox);
Alpine.data('arkLearnGuideModal', arkLearnGuideModal);
Alpine.data('arkOperationalClock', (config = {}) => arkOperationalClock(config));
Alpine.data('arkRoModeControl', (config = {}) => arkRoModeControl(config));
Alpine.data('arkWorkspaceModal', (config = {}) => arkWorkspaceModal(config));
Alpine.data('arkSavedWorkPicker', (config = {}) => arkSavedWorkPicker(config));
Alpine.data('arkDragonServiceAdvisor', (config = {}) => arkDragonServiceAdvisor(config));
Alpine.data('arkReviewEstimateNotes', (config = {}) => arkReviewEstimateNotes(config));
Alpine.data('arkDocumentAdd', (config = {}) => arkDocumentAdd(config));
Alpine.data('arkRoMention', (visits = []) => arkRoMention(visits));

Alpine.start();

initWorkspaceTabs();
initWorkspaceDirtyBindings();
initRoWorkspaceMemory();
initIntakeWorkspaceMemory();
initWorkItemQuickAdd();
initWorkRecentActivity();
initCommsWorkboard();
initOpsWorkboardTriage();
initCommsWorkspace();
initCommsNavPressure();
initOpsGlobalSearch();
initDepositBreakdowns();
initRepairOrderLifecycleSelect();
initRoFooterCompose();
initPartProcurementSelect();
initRoModeControl();
initWorkspaceStrip();
initNumericOnlyInputs();
initInspectionCaptureSurfaceCtas();
initStaffPresenceHeartbeat();
initWorkstationPresence();
initPublicSurfaceTheme();
import('preline').then(() => {
    window.HSStaticMethods?.autoInit();
});
