<?php

namespace Tests\Support;

use Illuminate\Support\Facades\DB;

final class RteLaborGuideFixtures
{
    public static function seedSmoke(): void
    {
        DB::table('rte_carlvl3')->insert([
            'lvl123_code' => '000300',
            'car_id_code' => 'DTGB',
            'car_desc' => 'ACADIA',
            'lo_yr' => '2007',
            'hi_yr' => '2014',
        ]);

        DB::table('rte_job_lku')->insert([
            [
                'job_id_code' => '11071Bx',
                'job_desc' => 'ADJUST A-C BELT',
                'eng_req' => 'B',
            ],
            [
                'job_id_code' => '1251',
                'job_desc' => '4 WHEEL ALIGNMENT',
                'eng_req' => 'B',
            ],
        ]);

        DB::table('rte_jobtbl')->insert([
            'jobid' => '11071',
            'mod_eng_code' => 'xxxx',
            'exception' => 'N',
        ]);

        DB::table('rte_lab')->insert([
            'lab_id' => '11071Bxx22299',
            'vehicle_segment' => 'Bxx',
            'lo_yr' => '0000',
            'hi_yr' => '9999',
            'com_flag' => 'N',
            'add_req' => '1',
            'model1' => 'DTGB',
            'model2' => null,
            'model3' => null,
            'model4' => null,
            'model5' => null,
            'model6' => null,
            'model7' => null,
            'model8' => null,
            'model9' => null,
            'eng1' => null,
            'eng2' => null,
            'eng3' => null,
            'eng4' => null,
            'eng5' => null,
            'eng6' => null,
            'eng7' => null,
            'eng8' => null,
            'eng9' => null,
            'add_id1' => '125',
            'add_hr1' => 0.3,
            'add_id2' => null,
            'add_hr2' => null,
            'add_id3' => null,
            'add_hr3' => null,
            'add_id4' => null,
            'add_hr4' => null,
            'add_id5' => null,
            'add_hr5' => null,
            'add_id6' => null,
            'add_hr6' => null,
            'add_id7' => null,
            'add_hr7' => null,
            'add_id8' => null,
            'add_hr8' => null,
            'add_id9' => null,
            'add_hr9' => null,
            'hi_hr' => 1.3,
            'avg_hr' => 1.1,
            'lo_hr' => 1.0,
        ]);
    }

    public static function seedRam2500Candidates(): void
    {
        DB::table('rte_carlvl3')->insert([
            [
                'lvl123_code' => '000100',
                'car_id_code' => 'DTEF',
                'car_desc' => 'C SERIES P-U C20-C2500',
                'lo_yr' => '1968',
                'hi_yr' => '2012',
            ],
            [
                'lvl123_code' => '000100',
                'car_id_code' => 'BTJT',
                'car_desc' => 'R 2500-3500 PICK-UP',
                'lo_yr' => '1993',
                'hi_yr' => '2014',
            ],
            [
                'lvl123_code' => '000100',
                'car_id_code' => 'BTTT',
                'car_desc' => 'R 2500-3500 4x4 PICK-UP',
                'lo_yr' => '1993',
                'hi_yr' => '2014',
            ],
            [
                'lvl123_code' => '000200',
                'car_id_code' => 'BTCF',
                'car_desc' => 'CARAVAN',
                'lo_yr' => '1984',
                'hi_yr' => '2014',
            ],
        ]);
    }

    public static function seedRam2500LaborRows(): void
    {
        self::seedRam2500Candidates();

        DB::table('rte_engtbl')->insert([
            [
                'mod_id_code' => 'BTJT',
                'eng_id_code' => 'B803A0',
                'eng_desc' => '5.7L MULTIPORT FI (HEMI)',
                'lo_yr' => '2003',
                'hi_yr' => '2014',
            ],
            [
                'mod_id_code' => 'BTTT',
                'eng_id_code' => 'B803A0',
                'eng_desc' => '5.7L MULTIPORT FI (HEMI)',
                'lo_yr' => '2003',
                'hi_yr' => '2014',
            ],
        ]);

        DB::table('rte_job_lku')->insert([
            [
                'job_id_code' => '3461',
                'job_desc' => 'R & R RADIATOR',
                'eng_req' => 'B',
            ],
            [
                'job_id_code' => '2641',
                'job_desc' => 'R & R FRONT DISC PADS',
                'eng_req' => 'B',
            ],
            [
                'job_id_code' => '1421',
                'job_desc' => 'DRAIN & FILL SYSTEM COOLING SYS',
                'eng_req' => 'B',
            ],
            [
                'job_id_code' => '1431',
                'job_desc' => 'COMBUSTION TEST COOLING SYSTEM',
                'eng_req' => 'B',
            ],
        ]);

        DB::table('rte_lab')->insert([
            [
                'lab_id' => '3461BTxx12199',
                'vehicle_segment' => 'BTxx',
                'lo_yr' => '1968',
                'hi_yr' => '2014',
                'com_flag' => 'N',
                'add_req' => '1',
                'model1' => null,
                'model2' => null,
                'model3' => null,
                'model4' => null,
                'model5' => null,
                'model6' => null,
                'model7' => null,
                'model8' => null,
                'model9' => null,
                'eng1' => 'B80xxx',
                'eng2' => null,
                'eng3' => null,
                'eng4' => null,
                'eng5' => null,
                'eng6' => null,
                'eng7' => null,
                'eng8' => null,
                'eng9' => null,
                'add_id1' => null,
                'add_hr1' => null,
                'add_id2' => null,
                'add_hr2' => null,
                'add_id3' => null,
                'add_hr3' => null,
                'add_id4' => null,
                'add_hr4' => null,
                'add_id5' => null,
                'add_hr5' => null,
                'add_id6' => null,
                'add_hr6' => null,
                'add_id7' => null,
                'add_hr7' => null,
                'add_id8' => null,
                'add_hr8' => null,
                'add_id9' => null,
                'add_hr9' => null,
                'hi_hr' => 1.2,
                'avg_hr' => 1.0,
                'lo_hr' => 0.8,
            ],
            [
                'lab_id' => '2641BTxx22299',
                'vehicle_segment' => 'BTxx',
                'lo_yr' => '0000',
                'hi_yr' => '9999',
                'com_flag' => 'N',
                'add_req' => '1',
                'model1' => null,
                'model2' => null,
                'model3' => null,
                'model4' => null,
                'model5' => null,
                'model6' => null,
                'model7' => null,
                'model8' => null,
                'model9' => null,
                'eng1' => null,
                'eng2' => null,
                'eng3' => null,
                'eng4' => null,
                'eng5' => null,
                'eng6' => null,
                'eng7' => null,
                'eng8' => null,
                'eng9' => null,
                'add_id1' => null,
                'add_hr1' => null,
                'add_id2' => null,
                'add_hr2' => null,
                'add_id3' => null,
                'add_hr3' => null,
                'add_id4' => null,
                'add_hr4' => null,
                'add_id5' => null,
                'add_hr5' => null,
                'add_id6' => null,
                'add_hr6' => null,
                'add_id7' => null,
                'add_hr7' => null,
                'add_id8' => null,
                'add_hr8' => null,
                'add_id9' => null,
                'add_hr9' => null,
                'hi_hr' => 1.3,
                'avg_hr' => 1.1,
                'lo_hr' => 1.0,
            ],
            [
                'lab_id' => '3461BTCF12298',
                'vehicle_segment' => 'BTCF',
                'lo_yr' => '1984',
                'hi_yr' => '2014',
                'com_flag' => 'N',
                'add_req' => '1',
                'model1' => null,
                'model2' => null,
                'model3' => null,
                'model4' => null,
                'model5' => null,
                'model6' => null,
                'model7' => null,
                'model8' => null,
                'model9' => null,
                'eng1' => 'B80xxx',
                'eng2' => null,
                'eng3' => null,
                'eng4' => null,
                'eng5' => null,
                'eng6' => null,
                'eng7' => null,
                'eng8' => null,
                'eng9' => null,
                'add_id1' => null,
                'add_hr1' => null,
                'add_id2' => null,
                'add_hr2' => null,
                'add_id3' => null,
                'add_hr3' => null,
                'add_id4' => null,
                'add_hr4' => null,
                'add_id5' => null,
                'add_hr5' => null,
                'add_id6' => null,
                'add_hr6' => null,
                'add_id7' => null,
                'add_hr7' => null,
                'add_id8' => null,
                'add_hr8' => null,
                'add_id9' => null,
                'add_hr9' => null,
                'hi_hr' => 2.5,
                'avg_hr' => 2.3,
                'lo_hr' => 2.1,
            ],
        ]);
    }

    public static function seedFourRunnerCandidates(): void
    {
        DB::table('rte_carlvl3')->insert([
            [
                'lvl123_code' => '000300',
                'car_id_code' => '7TDA',
                'car_desc' => '* 4-RUNNER',
                'lo_yr' => '1984',
                'hi_yr' => '2023',
            ],
            [
                'lvl123_code' => '000300',
                'car_id_code' => '7TDB',
                'car_desc' => '* 4-RUNNER 4X4',
                'lo_yr' => '1984',
                'hi_yr' => '2023',
            ],
        ]);
    }

    public static function seedFourRunnerLaborRows(): void
    {
        self::seedFourRunnerCandidates();

        DB::table('rte_job_lku')->insert([
            [
                'job_id_code' => '3461',
                'job_desc' => 'R & R RADIATOR',
                'eng_req' => 'S',
            ],
            [
                'job_id_code' => '2643',
                'job_desc' => 'R & R FRONT DISC PADS & REPLACE ROTORS',
                'eng_req' => 'B',
            ],
        ]);

        DB::table('rte_lab')->insert([
            [
                'lab_id' => '34617TDA12199',
                'vehicle_segment' => '7TDA',
                'lo_yr' => '1984',
                'hi_yr' => '1996',
                'com_flag' => 'N',
                'add_req' => '1',
                'model1' => null,
                'model2' => null,
                'model3' => null,
                'model4' => null,
                'model5' => null,
                'model6' => null,
                'model7' => null,
                'model8' => null,
                'model9' => null,
                'eng1' => null,
                'eng2' => null,
                'eng3' => null,
                'eng4' => null,
                'eng5' => null,
                'eng6' => null,
                'eng7' => null,
                'eng8' => null,
                'eng9' => null,
                'add_id1' => null,
                'add_hr1' => null,
                'add_id2' => null,
                'add_hr2' => null,
                'add_id3' => null,
                'add_hr3' => null,
                'add_id4' => null,
                'add_hr4' => null,
                'add_id5' => null,
                'add_hr5' => null,
                'add_id6' => null,
                'add_hr6' => null,
                'add_id7' => null,
                'add_hr7' => null,
                'add_id8' => null,
                'add_hr8' => null,
                'add_id9' => null,
                'add_hr9' => null,
                'hi_hr' => 1.1,
                'avg_hr' => 1.0,
                'lo_hr' => 0.8,
            ],
            [
                'lab_id' => '26437TDA12298',
                'vehicle_segment' => '7TDA',
                'lo_yr' => '1990',
                'hi_yr' => '2023',
                'com_flag' => 'N',
                'add_req' => '2',
                'model1' => null,
                'model2' => null,
                'model3' => null,
                'model4' => null,
                'model5' => null,
                'model6' => null,
                'model7' => null,
                'model8' => null,
                'model9' => null,
                'eng1' => null,
                'eng2' => null,
                'eng3' => null,
                'eng4' => null,
                'eng5' => null,
                'eng6' => null,
                'eng7' => null,
                'eng8' => null,
                'eng9' => null,
                'add_id1' => null,
                'add_hr1' => null,
                'add_id2' => null,
                'add_hr2' => null,
                'add_id3' => null,
                'add_hr3' => null,
                'add_id4' => null,
                'add_hr4' => null,
                'add_id5' => null,
                'add_hr5' => null,
                'add_id6' => null,
                'add_hr6' => null,
                'add_id7' => null,
                'add_hr7' => null,
                'add_id8' => null,
                'add_hr8' => null,
                'add_id9' => null,
                'add_hr9' => null,
                'hi_hr' => 2.3,
                'avg_hr' => 2.0,
                'lo_hr' => 1.4,
            ],
        ]);
    }
}
