<?php

/**
 * Popular OBD-II / check engine light codes — authority pages at /common-problems/p####.
 * Hand-authored tier-1 for high-search-volume codes; follows P0171 template.
 *
 * @return list<array<string, mixed>>
 */
return [
    [
        'slug' => 'p0300',
        'title' => 'P0300 Check Engine Code',
        'page_title' => 'P0300 Code: Random / Multiple Cylinder Misfire',
        'tier' => 1,
        'concern_prefill' => 'My check engine light is on with code P0300 — random or multiple cylinder misfire.',
        'meta_description' => 'P0300 check engine code in Colorado Springs? Random or multiple cylinder misfire explained in plain English — symptoms, if you can drive, common causes, and how LugsNPlugs checks misfire counts before replacing coils or plugs.',
        'problem' => 'Your engine is missing fire in more than one cylinder — or the computer cannot pin the miss to a single hole. That is what P0300 means: random or multiple cylinder misfire. Fuel is not burning cleanly in the combustion chamber, so you may feel a shake, lose power, or watch MPG drop. On Colorado hills and at altitude, weak spark or a lean air/fuel mix shows up fast under load. A flashing check engine light with P0300 is urgent — unburned fuel can overheat the catalytic converter before you know which plug or coil is at fault.',
        'symptoms' => [
            'Check engine light on — steady or flashing, with P0300 stored or pending',
            'Rough idle, stumble when you accelerate, or vibration at stoplights',
            'Loss of power climbing hills or merging onto I-25',
            'Fuel smell from the exhaust or worse MPG over the last few tanks',
            'P0300 showing up with cylinder-specific codes too (P0301 through P0308)',
        ],
        'can_drive_heading' => 'Can I keep driving with a P0300 code?',
        'can_drive' => [
            'Steady light with mild roughness — drive gently to a shop soon. Avoid hard acceleration and long climbs until it is scanned.',
            'A flashing check engine light means the engine is misfiring while you drive. Drive gently, don’t tow, and get it checked right away to protect the catalytic converter.',
            'Severe shaking, stalling in traffic, or a strong fuel smell — stop driving and call us.',
        ],
        'common_causes' => [
            'Worn spark plugs or failed ignition coils — most common on higher-mileage vehicles',
            'Vacuum leak or lean fuel trim stressing ignition when the engine is under load',
            'Low fuel pressure, a restricted injector, or bad fuel',
            'Compression loss — valve seal, burnt valve, or head gasket (after ignition is ruled out)',
            'Wrong spark plug gap or wrong plug type after DIY service',
        ],
        'often_confused_with' => [
            'P0171 or P0174 lean codes with no misfire counts climbing on the scan tool',
            'Engine mount vibration at idle only — no misfire counts in the data',
            'Transmission flare tied to shifts, not a steady miss at constant RPM',
            'Single-cylinder P0301 through P0308 without P0300 — one bad plug or coil vs. random misfire',
        ],
        'if_you_ignore' => [
            'Catalytic converter damage from repeated misfire events',
            'Fouled spark plugs and failed oxygen sensors',
            'One weak cylinder loading the rest when a coil-on-plug starts to fail',
            'What started as plugs often becomes converter and coil work if you wait',
        ],
        'repair_overview' => [
            'Read stored and pending codes, then look at live misfire counters for each cylinder',
            'Inspect plugs, boots, and coils on the affected bank — or all cylinders when P0300 is random',
            'Check fuel trim and vacuum leaks when misfire follows lean codes',
            'Compression or leak-down testing when ignition and fuel look good',
        ],
        'what_happens_next' => [
            'Tell us if the light flashes, when the roughness shows up (cold vs. hot, idle vs. under load), and any recent service.',
            'We scan live misfire data, road test when it is safe, and inspect ignition parts — not a default tune-up quote from the code alone.',
            'You see which cylinders are counting misfires before we recommend plugs, coils, or deeper engine work.',
            'We clear codes only after the root cause is verified fixed.',
        ],
        'faq' => [
            [
                'question' => 'What does P0300 mean?',
                'answer' => 'P0300 is Random/Multiple Cylinder Misfire Detected. The computer saw misfires in more than one cylinder, or could not isolate the fault to a single cylinder during its test window.',
            ],
            [
                'question' => 'Is P0300 serious?',
                'answer' => 'It can be. Mild rough idle is annoying. Active misfire under load — especially with a flashing light — can damage the catalytic converter quickly. How urgent it is depends on misfire counts and how the car feels.',
            ],
            [
                'question' => 'How does LugsNPlugs diagnose P0300?',
                'answer' => 'We review per-cylinder misfire counters, inspect plugs and coils, and check fuel trim and vacuum leaks when the data points that way — not a blind parts swap from the code definition.',
            ],
        ],
        'related_problem_slugs' => ['check-engine-light', 'rough-idle', 'p0171', 'p0420'],
    ],
    [
        'slug' => 'p0420',
        'title' => 'P0420 Check Engine Code',
        'page_title' => 'P0420 Code: Catalyst System Efficiency (Bank 1)',
        'tier' => 1,
        'concern_prefill' => 'My check engine light is on with code P0420 — catalyst system efficiency below threshold bank 1.',
        'meta_description' => 'P0420 catalytic converter code in Colorado Springs? What catalyst efficiency below threshold on bank 1 means in plain English, symptoms, if you can keep driving, and how LugsNPlugs rules out misfire and exhaust leaks before recommending a converter.',
        'problem' => 'Bank 1\'s catalytic converter is not scrubbing exhaust as well as it should — that is the claim behind P0420 (catalyst system efficiency below threshold). Oxygen sensors before and after the cat feed that judgment, so a lazy sensor, an exhaust leak, or an engine problem that already cooked the catalyst can look the same as a worn converter. Colorado shops see P0420 after ignored misfires, oil consumption, or quick code clears that never fixed the real issue. Proving the cat is actually bad takes more than reading the definition on a parts-store printout.',
        'symptoms' => [
            'Check engine light on with P0420 — often no obvious driveability change at first',
            'Failed emissions test or readiness monitors that will not complete',
            'Recent misfire codes, rich running, or blue or white exhaust smoke',
            'Rattling from under the vehicle — broken catalyst material inside the converter (separate from P0420 alone)',
            'P0420 showing up after exhaust or header work',
        ],
        'can_drive_heading' => 'Can I keep driving with a P0420 code?',
        'can_drive' => [
            'If the car runs normally and there is no misfire, you can usually drive to a shop for diagnosis. Emissions compliance is the immediate concern — not sudden breakdown.',
            'If you have active misfire, a flashing light, or a strong exhaust smell, fix the engine fault first. A new converter will fail again if misfire continues.',
            'Do not assume the catalytic converter is bad from the code alone. We verify sensors and engine health first.',
        ],
        'common_causes' => [
            'Aged or contaminated catalytic converter — high mileage, oil ash, or coolant contamination',
            'Failed downstream or upstream oxygen sensor skewing efficiency readings',
            'Exhaust leak before the downstream O2 sensor',
            'Unresolved misfire or rich running that damaged the catalyst',
            'Aftermarket exhaust without proper sensor placement',
        ],
        'often_confused_with' => [
            'P0430 — same fault on bank 2 (V6 and V8 engines)',
            'P0138 or P0158 high-voltage O2 codes — sensor circuit problem, not necessarily a bad converter',
            'Exhaust leak tick or smell — can set efficiency codes without needing a new cat',
            'Misfire P0300 — fix the engine first; the converter code may clear after repair',
        ],
        'if_you_ignore' => [
            'Failed emissions inspection when registration is due',
            'Continued misfire or oil burning destroys a replacement converter quickly',
            'Clearing the code without fixing the root cause wastes converter and labor',
            'Exhaust restriction from collapsed catalyst material — rare but serious if you hear rattling',
        ],
        'repair_overview' => [
            'Verify no active misfire; review fuel trim and freeze-frame data from when P0420 set',
            'Inspect the exhaust for leaks; test O2 sensor response and heater operation',
            'Compare bank 1 vs. bank 2 on V engines when applicable',
            'Recommend converter replacement only when sensors and engine health are proven',
        ],
        'what_happens_next' => [
            'Share mileage, any misfire history, and whether you need emissions testing soon.',
            'We scan live O2 data, inspect the exhaust, and confirm the engine is not still damaging the catalyst.',
            'You see sensor graphs and leak checks before a converter quote — not a default cat sale from P0420 alone.',
        ],
        'faq' => [
            [
                'question' => 'What does P0420 mean?',
                'answer' => 'P0420 is Catalyst System Efficiency Below Threshold — Bank 1. Bank 1 is the side of the engine that has cylinder 1. On engines with only one bank, it refers to the whole engine. The computer compared oxygen sensors and decided the catalyst is not converting exhaust effectively enough.',
            ],
            [
                'question' => 'Do I always need a new catalytic converter for P0420?',
                'answer' => 'No. Oxygen sensors, exhaust leaks, and engine problems can mimic a bad converter. We verify those before recommending a cat — especially if misfire or oil consumption is in the history.',
            ],
            [
                'question' => 'How does LugsNPlugs diagnose P0420?',
                'answer' => 'We rule out misfire and leaks, test O2 sensor behavior, and inspect the exhaust system. Converter replacement is quoted only when evidence supports it — not from the code definition alone.',
            ],
        ],
        'related_problem_slugs' => ['check-engine-light', 'p0300', 'p0430', 'rough-idle'],
    ],
    [
        'slug' => 'p0430',
        'title' => 'P0430 Check Engine Code',
        'page_title' => 'P0430 Code: Catalyst System Efficiency (Bank 2)',
        'tier' => 2,
        'concern_prefill' => 'My check engine light is on with code P0430 — catalyst system efficiency below threshold bank 2.',
        'meta_description' => 'P0430 check engine code in Colorado Springs? Catalyst efficiency bank 2 explained in plain English — how it differs from P0420, common causes, and how LugsNPlugs diagnoses before replacing a catalytic converter.',
        'problem' => 'Same catalyst-efficiency story as P0420, but on bank 2 — the side of a V engine that does not include cylinder 1. P0430 means that bank\'s catalytic converter is not cleaning exhaust well enough for the oxygen sensors to pass their monitor. A worn cat, a slow O2 sensor, or an exhaust leak can all set it. Verify engine health and sensors on that bank before assuming the converter failed — otherwise you buy hardware the real fault will destroy again.',
        'symptoms' => [
            'Check engine light with P0430 — may appear alone or with P0420',
            'Emissions test failure on bank 2 monitors',
            'History of misfire on bank 2 cylinders',
            'Exhaust or header work on one bank recently',
            'Often no noticeable driveability symptom until engine faults are present',
        ],
        'can_drive_heading' => 'Can I keep driving with a P0430 code?',
        'can_drive' => [
            'Similar to P0420 — if it runs normally without misfire, you can usually drive to diagnosis. Emissions compliance is the pressing issue.',
            'Fix active misfire on bank 2 before replacing a converter.',
            'Rattling exhaust or power loss needs inspection — not just a code clear.',
        ],
        'common_causes' => [
            'Worn catalytic converter on bank 2',
            'Downstream O2 sensor on bank 2 slow or reading wrong',
            'Exhaust leak affecting bank 2 sensor readings',
            'Bank 2 misfire or rich running that damaged the catalyst',
            'P0420 and P0430 together — both converters aged, or a systemic engine issue',
        ],
        'often_confused_with' => [
            'P0420 bank 1 — same diagnosis path, different bank',
            'Bank 2 misfire codes P0302, P0304, P0306, P0308 — fix ignition before blaming the cat',
            'O2 sensor heater codes on bank 2',
        ],
        'if_you_ignore' => [
            'Emissions failure at registration',
            'Repeat converter damage if bank 2 misfire continues',
            'Replacing one bank while the other fails shortly after on high-mileage V engines',
        ],
        'repair_overview' => [
            'Same verification path as P0420 — misfire, leaks, O2 response, then converter',
            'Compare both banks when only one side sets efficiency codes',
        ],
        'what_happens_next' => [
            'Call with engine size (V6 or V8) and whether P0420 is also stored.',
            'We scan both banks, inspect the exhaust, and test sensors before quoting bank 2 converter work.',
        ],
        'faq' => [
            [
                'question' => 'What is the difference between P0420 and P0430?',
                'answer' => 'P0420 is catalyst efficiency on bank 1. P0430 is bank 2. Bank 1 is the side of the engine that has cylinder 1. Bank 2 is the opposite side on a V engine. Each bank has its own converter and downstream oxygen sensor. Diagnosis is the same — check engine health and sensors before replacing hardware.',
            ],
            [
                'question' => 'How do you diagnose P0430?',
                'answer' => 'Same path as P0420: misfire counters, exhaust leaks, O2 sensor tests, then converter condition — bank-specific, not a generic cat quote.',
            ],
        ],
        'related_problem_slugs' => ['p0420', 'check-engine-light', 'p0300'],
    ],
    [
        'slug' => 'p0174',
        'title' => 'P0174 Check Engine Code',
        'page_title' => 'P0174 Code: System Too Lean (Bank 2)',
        'tier' => 1,
        'concern_prefill' => 'My check engine light is on with code P0174 — system too lean bank 2.',
        'meta_description' => 'P0174 check engine code in Colorado Springs? System too lean bank 2 explained in plain English — symptoms, driving safety, common causes, and how LugsNPlugs checks fuel trim on bank 2 before recommending parts.',
        'problem' => 'Too much air or not enough fuel on bank 2 — that lean mix is what P0174 (system too lean) is flagging. Bank 2 is the opposite side from bank 1 on a V engine (no cylinder 1). Lean running can cause misfire, hesitation, and catalytic converter damage if it goes on. On a four-cylinder, P0174 often rides with P0171 when both banks are reported. Colorado altitude can nudge fuel trim when cold; we still verify live data rather than clearing the light and hoping.',
        'symptoms' => [
            'Check engine light with P0174 — alone or with P0171',
            'Rough idle, hesitation, or stumble on light throttle',
            'Poor fuel economy; lean codes on bank 2 cylinders on a V engine',
            'Code after intake work, PCV service, or MAF cleaning',
            'Vacuum leak hiss under the hood — sometimes affects one bank on V layouts',
        ],
        'can_drive_heading' => 'Can I keep driving with a P0174 code?',
        'can_drive' => [
            'Steady light and smooth driving — careful trip to diagnosis soon. Sustained lean running can damage the catalytic converter.',
            'Misfire, flashing light, or severe hesitation — reduce load and get scanned quickly.',
            'Fuel smell, heavy smoke, or repeated stalling — stop driving.',
        ],
        'common_causes' => [
            'Vacuum leak affecting bank 2 intake runner or PCV routing',
            'MAF sensor skewing fuel delivery to both banks',
            'Weak fuel pump or restricted injector on bank 2',
            'Exhaust leak before bank 2 upstream oxygen sensor',
            'EVAP purge valve stuck open',
        ],
        'often_confused_with' => [
            'P0171 lean bank 1 — same kind of problem, opposite bank',
            'P0300 misfire without lean fuel trim in the data',
            'P0101 MAF circuit — may set lean codes on both banks',
        ],
        'if_you_ignore' => [
            'Catalytic converter overheating from lean combustion',
            'Bank 2 misfire and plug fouling',
            'Small vacuum leaks growing into drivability complaints',
        ],
        'repair_overview' => [
            'Live short-term and long-term fuel trim on both banks',
            'Smoke test or targeted leak detection for bank-specific leaks on V engines',
            'Fuel pressure and injector balance when trim points to delivery',
        ],
        'what_happens_next' => [
            'Note V6, V8, or four-cylinder and whether P0171 is also present.',
            'We compare bank 1 and bank 2 fuel trim, inspect for leaks, and verify MAF and fuel delivery before parts.',
        ],
        'faq' => [
            [
                'question' => 'What does P0174 mean?',
                'answer' => 'P0174 is System Too Lean — Bank 2. Bank 2 is the side of the engine that does not include cylinder 1 on a V engine. On a four-cylinder, bank 2 often refers to the whole engine. The computer measured more air or less fuel than expected on that bank.',
            ],
            [
                'question' => 'Is P0174 the same as P0171?',
                'answer' => 'Same type of fault, different bank. On many vehicles both codes appear together when the issue affects overall airflow — MAF, fuel pressure — rather than one bank only.',
            ],
            [
                'question' => 'How does LugsNPlugs diagnose P0174?',
                'answer' => 'We read live fuel trim per bank, inspect for vacuum leaks and MAF contamination, and test fuel delivery — same evidence path as P0171, bank-aware.',
            ],
        ],
        'related_problem_slugs' => ['p0171', 'check-engine-light', 'rough-idle'],
    ],
    [
        'slug' => 'p0442',
        'title' => 'P0442 Check Engine Code',
        'page_title' => 'P0442 Code: EVAP System Small Leak Detected',
        'tier' => 1,
        'concern_prefill' => 'My check engine light is on with code P0442 — EVAP system small leak detected.',
        'meta_description' => 'P0442 EVAP small leak code in Colorado Springs? Often gas cap related — symptoms, if you can drive, common causes, and how LugsNPlugs smoke-tests the evaporative emissions system before replacing parts.',
        'problem' => 'Something between the gas tank and the engine is not holding pressure during the car\'s EVAP self-test — that is P0442, evaporative emissions small leak detected. The gas cap gets blamed first (and sometimes it is the fix), but cracked hoses, a stuck purge valve, or a leaking filler neck show up just as often on Colorado vehicles that see big temperature swings. Driveability is usually fine; the light stays on and emissions can fail until the leak is found and sealed.',
        'symptoms' => [
            'Check engine light on — the car may drive completely normally',
            'Code appeared shortly after filling with gas or leaving the cap loose',
            'Faint fuel smell near the rear of the vehicle — less common with small leaks',
            'Failed emissions test — EVAP monitor not ready or leak detected',
            'P0442 with P0455 or P0440 family codes in history',
        ],
        'can_drive_heading' => 'Can I keep driving with a P0442 code?',
        'can_drive' => [
            'Yes — EVAP small leak codes do not usually affect engine safety or power.',
            'Tighten the gas cap until it clicks, drive a few days, and see if the monitor completes. If the light returns, schedule EVAP diagnosis.',
            'Strong fuel smell or visible leaking at the tank — minimize driving and get inspection.',
        ],
        'common_causes' => [
            'Loose, missing, or worn gas cap seal',
            'Cracked EVAP hose at the canister, purge valve, or tank',
            'Leaking purge or vent solenoid',
            'Rust or corrosion at the filler neck — common on older trucks and SUVs',
            'Aftermarket gas cap that does not seal to OEM spec',
        ],
        'often_confused_with' => [
            'P0455 large leak — same system, bigger leak threshold',
            'P0440 general EVAP fault — broader than P0442 alone',
            'Rich running or fuel trim codes — EVAP usually does not change idle quality',
        ],
        'if_you_ignore' => [
            'Check engine light stays on — other faults may hide behind it',
            'Emissions test failure at registration',
            'Small hose cracks growing into P0455 large leak codes',
            'Fuel vapor smell if the leak worsens near the tank',
        ],
        'repair_overview' => [
            'Verify gas cap seal and inspect visible EVAP hoses in the engine bay',
            'Smoke test the EVAP system to locate small leaks when the cap is ruled out',
            'Test purge and vent valve operation with scan tool commands',
        ],
        'what_happens_next' => [
            'Try a proper gas cap tighten first if the light just appeared after fueling.',
            'We smoke-test when the code returns — pinpoints small leaks faster than guessing at hoses.',
            'You see where the leak is before we quote valves, caps, or tank components.',
        ],
        'faq' => [
            [
                'question' => 'What does P0442 mean?',
                'answer' => 'P0442 is EVAP System Small Leak Detected. The car\'s emissions system found a leak too small for the large-leak threshold but big enough to fail the monitor.',
            ],
            [
                'question' => 'Will a new gas cap fix P0442?',
                'answer' => 'Sometimes — if the cap seal is worn or was left loose. If a quality OEM-style cap does not clear the code after drive cycles, smoke testing finds the real leak.',
            ],
            [
                'question' => 'How does LugsNPlugs diagnose P0442?',
                'answer' => 'We inspect the cap and visible hoses, then smoke-test the EVAP system when needed. We do not replace canisters or valves without locating the leak.',
            ],
        ],
        'related_problem_slugs' => ['p0455', 'check-engine-light'],
    ],
    [
        'slug' => 'p0455',
        'title' => 'P0455 Check Engine Code',
        'page_title' => 'P0455 Code: EVAP System Large Leak Detected',
        'tier' => 1,
        'concern_prefill' => 'My check engine light is on with code P0455 — EVAP system large leak detected.',
        'meta_description' => 'P0455 EVAP large leak code in Colorado Springs? Bigger evaporative leak than P0442 — gas cap, hoses, and purge valves. If you can drive and how LugsNPlugs smoke-tests before replacing EVAP parts.',
        'problem' => 'Fuel vapor is escaping the sealed path between the tank and the engine in a big way — P0455 is EVAP system large leak detected. Leaving the gas cap off after a fill-up still sets it often, but a disconnected hose, open purge valve, or damaged tank seal can trip the monitor just as fast. The engine usually runs fine; what you notice is the light, possible fuel smell, and an emissions monitor that will not pass until the leak is sealed.',
        'symptoms' => [
            'Check engine light on right after getting gas — cap left off or loose',
            'P0455 with noticeable fuel smell at the rear of the vehicle',
            'Failed EVAP monitor on emissions test',
            'Recent underbody work or skid plate removal that disturbed EVAP lines',
            'May appear with P0442 if leak size varies between tests',
        ],
        'can_drive_heading' => 'Can I keep driving with a P0455 code?',
        'can_drive' => [
            'If the cap was left off, reinstall and tighten — the code may clear after drive cycles if no other leak exists.',
            'Normal driving is usually fine for engine safety. Address EVAP before emissions testing.',
            'Strong fuel smell or visible wetness at the tank — park outside, minimize ignition sources, and schedule inspection.',
        ],
        'common_causes' => [
            'Gas cap missing, loose, or wrong cap for the vehicle',
            'Disconnected or broken EVAP hose at purge valve or charcoal canister',
            'Purge solenoid stuck open',
            'Damaged filler neck or tank seal',
            'Rodent damage to rubber EVAP lines in the engine bay',
        ],
        'often_confused_with' => [
            'P0442 small leak — same system, different threshold',
            'Fuel leak at the tank — safety issue beyond the EVAP monitor',
            'Rich running codes — EVAP large leak rarely changes idle',
        ],
        'if_you_ignore' => [
            'Emissions failure and persistent check engine light',
            'Fuel vapor odor if the leak is at the tank or filler',
            'Missed easy fix (cap) turning into unnecessary parts replacement elsewhere',
        ],
        'repair_overview' => [
            'Confirm cap presence and seal quality first',
            'Visual inspection of engine-bay EVAP hoses and purge valve connections',
            'Smoke test when cap and obvious hoses look good',
        ],
        'what_happens_next' => [
            'Check whether the cap was left loose after your last fill-up.',
            'We inspect and smoke-test to find large leaks quickly — often a hose or cap, not a full system replacement.',
        ],
        'faq' => [
            [
                'question' => 'What does P0455 mean?',
                'answer' => 'P0455 is EVAP System Large Leak Detected. The sealed fuel vapor system failed a pressure test because a significant leak was found — commonly the gas cap, a disconnected hose, or an open purge valve.',
            ],
            [
                'question' => 'Is P0455 serious for the engine?',
                'answer' => 'Usually not for drivability — it is an emissions monitor fault. Fuel smell or visible leaking is a separate safety concern that should be inspected promptly.',
            ],
            [
                'question' => 'How does LugsNPlugs diagnose P0455?',
                'answer' => 'Cap and hose inspection first, then smoke testing. We locate the leak before quoting canisters, valves, or tank parts.',
            ],
        ],
        'related_problem_slugs' => ['p0442', 'check-engine-light'],
    ],
    [
        'slug' => 'p0128',
        'title' => 'P0128 Check Engine Code',
        'page_title' => 'P0128 Code: Coolant Thermostat Below Regulating Temperature',
        'tier' => 1,
        'concern_prefill' => 'My check engine light is on with code P0128 — coolant thermostat below regulating temperature.',
        'meta_description' => 'P0128 thermostat code in Colorado Springs? Engine not reaching proper temperature — symptoms, if you can drive, stuck-open thermostat causes, and how LugsNPlugs verifies cooling system data before replacing parts.',
        'problem' => 'The coolant is not getting hot enough, fast enough — your engine is running cool when it should be at operating temperature. That is P0128: coolant thermostat below regulating temperature. A thermostat stuck open is the usual culprit, though a wrong-temp thermostat, a cooling fan that never shuts off, or a skewed coolant temperature sensor can set the same light. In Colorado winters that means wasted fuel, rich warm-up running, and lukewarm heat from the vents until the cooling system is sorted.',
        'symptoms' => [
            'Check engine light with P0128 — engine may run otherwise fine',
            'Temperature gauge stays low on highway drives',
            'Heater blows lukewarm or takes forever to warm the cabin',
            'Poor fuel economy in cold weather',
            'Code may appear with P0125 or cooling fan-related faults',
        ],
        'can_drive_heading' => 'Can I keep driving with a P0128 code?',
        'can_drive' => [
            'Yes for short term — the engine is running cool, not overheating. Schedule thermostat diagnosis before the next cold snap.',
            'If the gauge goes hot, not cold, that is a different problem — see overheating guidance.',
            'Long-term cool running increases fuel use and emissions — worth fixing, not years of putting it off.',
        ],
        'common_causes' => [
            'Thermostat stuck open — most common',
            'Wrong thermostat temperature rating installed previously',
            'Coolant temperature sensor reading low',
            'Cooling fan stuck on or shorted — less common',
            'Low coolant level affecting sensor accuracy',
        ],
        'often_confused_with' => [
            'Engine overheating — opposite symptom (hot gauge, steam)',
            'P0125 insufficient coolant temperature for closed-loop fuel control',
            'Bad cabin heater core — heat issue without necessarily setting P0128',
        ],
        'if_you_ignore' => [
            'Poor winter heat and higher fuel bills all season',
            'Increased engine wear from prolonged rich warm-up running',
            'Emissions monitor failures from never reaching closed-loop',
            'Replacing only the thermostat without verifying the sensor if that was the real problem',
        ],
        'repair_overview' => [
            'Review live coolant temperature vs. ambient on a road test',
            'Verify thermostat opening temperature and fan operation',
            'Confirm coolant level and sensor plausibility before replacing parts',
        ],
        'what_happens_next' => [
            'Tell us if the heat is weak and whether the gauge ever reaches the middle.',
            'We compare scan data to the gauge, inspect the thermostat, and verify the sensor — not a default thermostat from P0128 alone.',
        ],
        'faq' => [
            [
                'question' => 'What does P0128 mean?',
                'answer' => 'P0128 means Coolant Thermostat Below Regulating Temperature. The engine coolant did not reach the expected operating temperature in the time the computer allows — usually a stuck-open thermostat or a sensor or fan issue.',
            ],
            [
                'question' => 'Can P0128 cause overheating?',
                'answer' => 'No — P0128 is about running too cool. Overheating is a separate failure path: stuck closed thermostat, leaks, or fan failure.',
            ],
            [
                'question' => 'How does LugsNPlugs diagnose P0128?',
                'answer' => 'We verify live coolant temp data on a drive, inspect thermostat operation, and check the sensor and fan before recommending a thermostat replacement.',
            ],
        ],
        'related_problem_slugs' => ['check-engine-light', 'engine-overheating', 'subaru-overheating'],
    ],
    [
        'slug' => 'p0101',
        'title' => 'P0101 Check Engine Code',
        'page_title' => 'P0101 Code: MAF Circuit Range / Performance',
        'tier' => 2,
        'concern_prefill' => 'My check engine light is on with code P0101 — mass airflow circuit range or performance.',
        'meta_description' => 'P0101 MAF sensor code in Colorado Springs? Mass airflow circuit performance explained in plain English — symptoms, driving safety, dirty MAF vs. vacuum leaks, and how LugsNPlugs verifies airflow data before replacing the sensor.',
        'problem' => 'The computer is not getting a believable air measurement from the mass airflow (MAF) sensor — that mismatch is P0101, MAF circuit range/performance. A dirty hot wire, an air leak after the sensor, or a failing MAF can set it, often alongside lean codes P0171 and P0174 and a rough idle. Oil from oiled reusable filters is a frequent culprit on cars serviced at home or quick-lube shops. Cleaning, fixing an intake boot, or replacing the sensor only makes sense after live airflow data and a leak check back that up.',
        'symptoms' => [
            'Check engine light with P0101 — may include P0171 or P0174',
            'Rough idle, hesitation, or stall at a stop',
            'Poor acceleration or hunting RPM at steady throttle',
            'Code after air filter or intake boot service',
            'Worse performance at altitude or under load',
        ],
        'can_drive_heading' => 'Can I keep driving with a P0101 code?',
        'can_drive' => [
            'Mild symptoms — drive gently to a shop. Take it easy until it is scanned.',
            'Stalling in traffic or severe hesitation — schedule diagnosis immediately.',
            'Do not clean the MAF with aggressive chemicals at home — wrong cleaners damage the element.',
        ],
        'common_causes' => [
            'Contaminated MAF sensor from oiled filters or debris',
            'Intake boot crack or loose clamp after the MAF',
            'Failing MAF sensor element',
            'Vacuum leak downstream affecting measured airflow',
            'Exhaust leak skewing fuel trim — less common with P0101 alone',
        ],
        'often_confused_with' => [
            'P0171 lean — may be a result of a bad MAF reading, not a separate root cause',
            'Dirty throttle body — idle issue without MAF range fault',
            'MAP sensor codes on speed-density engines — different sensor',
        ],
        'if_you_ignore' => [
            'Lean running and catalyst damage',
            'Worsening stall and poor fuel economy',
            'Replacing the MAF without fixing intake leaks — code returns',
        ],
        'repair_overview' => [
            'Inspect intake boot and filter installation',
            'Compare MAF grams-per-second to spec at idle and off idle',
            'Clean MAF with appropriate cleaner only when data supports contamination',
        ],
        'what_happens_next' => [
            'Mention recent filter changes or intake work when you call or book.',
            'We review live MAF data and inspect the intake tract before recommending a sensor.',
        ],
        'faq' => [
            [
                'question' => 'What does P0101 mean?',
                'answer' => 'P0101 is Mass or Volume Air Flow Circuit Range/Performance Problem. The MAF sensor signal is outside the expected range for the engine load and RPM.',
            ],
            [
                'question' => 'Should I replace the MAF for P0101?',
                'answer' => 'Not always. We check intake leaks and contamination first. We quote a new sensor only when it fails plausibility checks after cleaning and leak verification.',
            ],
            [
                'question' => 'Can a dirty air filter cause P0101?',
                'answer' => 'Usually it is a contaminated MAF element, a cracked intake boot, or a failing sensor — not the filter alone. We inspect the whole intake path before replacing the MAF.',
            ],
        ],
        'related_problem_slugs' => ['p0171', 'rough-idle', 'check-engine-light'],
    ],
    [
        'slug' => 'p0301',
        'title' => 'P0301 Check Engine Code',
        'page_title' => 'P0301 Code: Cylinder 1 Misfire Detected',
        'tier' => 2,
        'concern_prefill' => 'My check engine light is on with code P0301 — cylinder 1 misfire detected.',
        'meta_description' => 'P0301 cylinder 1 misfire code in Colorado Springs? What it means in plain English, if you can drive, coil and plug causes, and how LugsNPlugs isolates cylinder 1 before recommending parts.',
        'problem' => 'Cylinder 1 is the one dropping the ball — fuel is not burning cleanly in that hole alone. P0301 is cylinder 1 misfire detected, which is narrower than P0300 (random or multiple). Most of the time it is ignition: spark plug, coil, or boot on that cylinder, sometimes the injector. A flashing light with P0301 still risks catalytic converter damage from unburned fuel, so the urgency stays high even when the scan tool already named the cylinder.',
        'symptoms' => [
            'Check engine light — may flash under load with active misfire',
            'Rough idle or stumble you can feel at low speed',
            'P0301 alone or with P0300',
            'Recent tune-up where cylinder 1 plug or coil was disturbed',
            'Fuel trim normal or lean on the bank that includes cylinder 1',
        ],
        'can_drive_heading' => 'Can I keep driving with a P0301 code?',
        'can_drive' => [
            'Steady light with mild roughness — gentle drive to diagnosis soon.',
            'Flashing light — reduce load immediately; same urgency as P0300.',
            'Do not swap coils randomly without confirming cylinder 1 counts on a scan tool.',
        ],
        'common_causes' => [
            'Failed coil-on-plug or spark plug on cylinder 1',
            'Cracked plug insulator or wrong plug gap',
            'Injector restriction on cylinder 1',
            'Low compression on cylinder 1 (after ignition is ruled out)',
            'Vacuum leak affecting cylinder 1 runner on some intakes',
        ],
        'often_confused_with' => [
            'P0300 random misfire — multiple cylinders or unstable counts',
            'P0302 through P0308 — other cylinders; a swap test isolates coil-related faults',
        ],
        'if_you_ignore' => [
            'Catalyst damage from cylinder 1 misfire under load',
            'Coil failure spreading heat to neighboring components',
            'Fouled plug becoming hard to remove',
        ],
        'repair_overview' => [
            'Confirm misfire counts on cylinder 1 with a scan tool',
            'Inspect plug and coil; swap coil test when safe and applicable',
            'Injector and compression tests when ignition looks good',
        ],
        'what_happens_next' => [
            'Call with whether the light flashes and whether roughness is constant or only when cold.',
            'We isolate cylinder 1 on scan data before quoting plugs, coils, or deeper work.',
        ],
        'faq' => [
            [
                'question' => 'What does P0301 mean?',
                'answer' => 'P0301 is Cylinder 1 Misfire Detected. Cylinder 1 is the reference cylinder for bank 1 on your engine. The computer counted enough misfire events on that cylinder to store a code.',
            ],
            [
                'question' => 'Can I swap the coil to test P0301?',
                'answer' => 'On some engines, moving the coil to another cylinder and watching misfire counts move with it speeds diagnosis. We do that when the design allows — instead of guessing at parts.',
            ],
            [
                'question' => 'Is P0301 an emergency?',
                'answer' => 'A steady light with mild roughness — get it scanned soon. A flashing light means the engine is misfiring while you drive; drive gently and come in quickly to protect the catalytic converter.',
            ],
        ],
        'related_problem_slugs' => ['p0300', 'rough-idle', 'check-engine-light'],
    ],
    [
        'slug' => 'p0302',
        'title' => 'P0302 Check Engine Code',
        'page_title' => 'P0302 Code: Cylinder 2 Misfire Detected',
        'tier' => 2,
        'concern_prefill' => 'My check engine light is on with code P0302 — cylinder 2 misfire detected.',
        'meta_description' => 'P0302 cylinder 2 misfire in Colorado Springs? Symptoms, driving safety, and how LugsNPlugs verifies cylinder 2 ignition before replacing coils or plugs.',
        'problem' => 'One cylinder is missing — this time cylinder 2 in your engine\'s firing order. P0302 names that miss so diagnosis can stay on that hole: coil, plug, injector, or compression. You may feel the same shake or stumble as other misfire codes; the difference is the scan tool already pointed at position 2. A flashing light still means unburned fuel can hurt the catalytic converter, so treat active misfire with the same urgency as P0301.',
        'symptoms' => [
            'Check engine light with P0302 stored or pending',
            'Rough idle or hesitation; may feel like P0300 if counts jump around',
            'Flashing light under acceleration — active misfire',
            'After water intrusion or oil in the plug well on bank 1',
        ],
        'can_drive_heading' => 'Can I keep driving with a P0302 code?',
        'can_drive' => [
            'Same guidance as P0301 — gentle driving if the light is steady; stop aggressive driving if it is flashing.',
            'Oil in the coil boot — diagnose before repeated starts wash oil into the catalyst.',
        ],
        'common_causes' => [
            'Ignition coil or spark plug on cylinder 2',
            'Oil leaking into the plug tube from a valve cover gasket',
            'Injector fault on cylinder 2',
            'Compression loss on cylinder 2',
        ],
        'often_confused_with' => ['P0300', 'P0301', 'P0303'],
        'if_you_ignore' => ['Catalyst damage from unburned fuel', 'Oil-fouled coil boot becoming a repeat misfire'],
        'repair_overview' => ['Misfire counts on cylinder 2', 'Inspect plug well for oil', 'Coil and plug test'],
        'what_happens_next' => [
            'Call with when it misfires and any oil smell under the hood.',
            'We confirm cylinder 2 on live data before quoting parts.',
        ],
        'faq' => [
            [
                'question' => 'What does P0302 mean?',
                'answer' => 'P0302 is Cylinder 2 Misfire Detected. The computer logged repeated misfire events on the cylinder in the number 2 firing position for your engine — not necessarily the second cylinder from the front.',
            ],
        ],
        'related_problem_slugs' => ['p0300', 'p0301', 'check-engine-light'],
    ],
    [
        'slug' => 'p0303',
        'title' => 'P0303 Check Engine Code',
        'page_title' => 'P0303 Code: Cylinder 3 Misfire Detected',
        'tier' => 2,
        'concern_prefill' => 'My check engine light is on with code P0303 — cylinder 3 misfire detected.',
        'meta_description' => 'P0303 cylinder 3 misfire in Colorado Springs? What the code means in plain English, if you can drive, and how LugsNPlugs isolates cylinder 3 before recommending ignition parts.',
        'problem' => 'Cylinder 3 is misfiring — combustion in that cylinder is incomplete enough for the computer to store P0303. On many V6 engines, cylinder 3 sits on bank 2, so lean codes like P0174 can ride along when that bank is short on fuel. Ignition on cylinder 3 (plug, coil, boot) is the first check; injectors and compression come after. Keep the load light if the light is flashing — unburned fuel still threatens the catalytic converter.',
        'symptoms' => [
            'Check engine light with P0303',
            'Rough running or shake at idle',
            'May appear with P0174 on bank 2 V6 layouts',
            'Flashing light when misfire is active under load',
        ],
        'can_drive_heading' => 'Can I keep driving with a P0303 code?',
        'can_drive' => [
            'Steady light — schedule diagnosis; drive gently.',
            'Flashing light — treat as urgent misfire; protect the catalytic converter.',
        ],
        'common_causes' => [
            'Coil or plug on cylinder 3',
            'Bank 2 vacuum leak contributing to lean misfire',
            'Injector on cylinder 3',
            'Compression issue on cylinder 3',
        ],
        'often_confused_with' => ['P0300', 'P0174', 'P0304'],
        'if_you_ignore' => ['Converter damage from unburned fuel', 'Bank 2 lean and misfire compounding'],
        'repair_overview' => ['Cylinder 3 misfire counters', 'Ignition inspection', 'Bank 2 fuel trim if lean codes are present'],
        'what_happens_next' => [
            'Call with engine type (I4, V6, V8) and any bank 2 lean codes.',
            'We isolate cylinder 3 on live data before quoting parts.',
        ],
        'faq' => [
            [
                'question' => 'What does P0303 mean?',
                'answer' => 'P0303 is Cylinder 3 Misfire Detected. The computer logged enough misfire events on cylinder 3 to store a code. On a V6, cylinder 3 is often on bank 2 — the side that does not include cylinder 1.',
            ],
        ],
        'related_problem_slugs' => ['p0300', 'p0174', 'check-engine-light'],
    ],
    [
        'slug' => 'p0304',
        'title' => 'P0304 Check Engine Code',
        'page_title' => 'P0304 Code: Cylinder 4 Misfire Detected',
        'tier' => 2,
        'concern_prefill' => 'My check engine light is on with code P0304 — cylinder 4 misfire detected.',
        'meta_description' => 'P0304 cylinder 4 misfire in Colorado Springs? Common on four-cylinder engines — symptoms, driving safety, and LugsNPlugs diagnosis before coil or plug replacement.',
        'problem' => 'On a lot of four-cylinder engines, cylinder 4 is the rearmost plug — hardest to reach, easiest to leave with a loose boot after DIY work. When that hole misfires, you get P0304: cylinder 4 misfire detected. Fuel is not burning cleanly there, so idle can feel rough and a flashing light under load still risks catalytic converter damage. Diagnosis starts with the plug, coil, and boot on cylinder 4 before chasing injectors or compression.',
        'symptoms' => [
            'P0304 on four-cylinder engines — very common isolated misfire code',
            'Rough idle, especially when cold',
            'May set with P0300 if counts spread to other cylinders',
            'After spark plug service where cylinder 4 is against the firewall',
        ],
        'can_drive_heading' => 'Can I keep driving with a P0304 code?',
        'can_drive' => [
            'Gentle driving to the shop if the light is steady.',
            'Flashing light — reduce throttle; misfire is active.',
        ],
        'common_causes' => [
            'Spark plug or coil on cylinder 4',
            'Loose coil boot after recent plug change',
            'Injector on cylinder 4',
            'Compression loss',
        ],
        'often_confused_with' => ['P0300', 'P0303'],
        'if_you_ignore' => ['Catalyst damage on short commutes', 'Repeat misfire from a loose boot'],
        'repair_overview' => ['Cylinder 4 misfire counts', 'Inspect plug and boot access', 'Coil test'],
        'what_happens_next' => [
            'Mention recent plug work when you call — cylinder 4 is often the one that gets disturbed.',
            'We verify misfire counts on cylinder 4 before quoting parts.',
        ],
        'faq' => [
            [
                'question' => 'What does P0304 mean?',
                'answer' => 'P0304 is Cylinder 4 Misfire Detected — isolated misfire on the cylinder in the number 4 firing position for your engine, not necessarily the fourth cylinder from the front.',
            ],
            [
                'question' => 'Is P0304 common on 4-cylinder cars?',
                'answer' => 'Yes — on many inline fours, P0304 shows up when one coil or plug fails on the rearmost cylinder. We still confirm on scan data before replacing anything.',
            ],
        ],
        'related_problem_slugs' => ['p0300', 'rough-idle', 'check-engine-light'],
    ],
    [
        'slug' => 'p0401',
        'title' => 'P0401 Check Engine Code',
        'page_title' => 'P0401 Code: EGR Flow Insufficient Detected',
        'tier' => 2,
        'concern_prefill' => 'My check engine light is on with code P0401 — EGR flow insufficient detected.',
        'meta_description' => 'P0401 EGR code in Colorado Springs? Exhaust gas recirculation flow insufficient — symptoms, if you can drive, carbon-clogged EGR causes, and how LugsNPlugs tests flow before replacing valves.',
        'problem' => 'When the computer asks for exhaust gas recirculation, not enough exhaust is getting back into the intake — that shortfall is P0401 (EGR flow insufficient). Carbon often clogs the EGR valve or passages; a failed valve or a sensor that under-reports flow can set the same light. Some drivers feel ping on acceleration or a rough idle if the valve sticks open; plenty of others only notice the check engine light until emissions testing comes due.',
        'symptoms' => [
            'Check engine light with P0401',
            'Light ping or knock on acceleration under load',
            'Rough idle if the EGR valve hangs open',
            'Failed emissions test — NOx related',
            'High mileage or short-trip driving history (carbon buildup)',
        ],
        'can_drive_heading' => 'Can I keep driving with a P0401 code?',
        'can_drive' => [
            'Usually yes for normal commuting — schedule diagnosis before emissions testing.',
            'Heavy ping under load — ease off the throttle; prolonged ping can harm combustion chambers.',
            'Severe idle stumble — get scanned; a stuck EGR can affect drivability.',
        ],
        'common_causes' => [
            'Carbon-clogged EGR valve or intake passages',
            'Failed EGR valve motor or position sensor',
            'Restricted EGR tube or cooler (if equipped)',
            'DPFE or pressure sensor fault reporting low flow incorrectly',
        ],
        'often_confused_with' => [
            'P0402 excessive EGR flow — opposite fault',
            'Vacuum leak — may affect idle without P0401',
        ],
        'if_you_ignore' => [
            'Emissions test failure',
            'Carbon blockage worsening — harder cleaning later',
            'Ping under load on mountain grades',
        ],
        'repair_overview' => [
            'Command EGR with a scan tool and verify pintle movement',
            'Inspect passages; clean or replace valve based on evidence',
            'Test DPFE or pressure sensors when the valve moves but the code returns',
        ],
        'what_happens_next' => [
            'Call with mileage and whether you need emissions testing soon.',
            'We test EGR operation before quoting valve replacement or cleaning labor.',
        ],
        'faq' => [
            [
                'question' => 'What does P0401 mean?',
                'answer' => 'P0401 is EGR Flow Insufficient Detected. The engine expected more exhaust gas recirculation than the system delivered during a monitor test.',
            ],
            [
                'question' => 'Can I clean the EGR valve myself?',
                'answer' => 'Carbon clogging is common, but stuck passages and sensor faults look similar. We test flow and valve movement first so you are not fighting the wrong fix.',
            ],
        ],
        'related_problem_slugs' => ['check-engine-light', 'rough-idle'],
    ],
    [
        'slug' => 'p0340',
        'title' => 'P0340 Check Engine Code',
        'page_title' => 'P0340 Code: Camshaft Position Sensor Circuit',
        'tier' => 2,
        'concern_prefill' => 'My check engine light is on with code P0340 — camshaft position sensor circuit malfunction.',
        'meta_description' => 'P0340 camshaft position sensor code in Colorado Springs? No-start and stall risk explained in plain English — wiring vs. sensor causes, and how LugsNPlugs tests the cam signal before replacing parts.',
        'problem' => 'The computer cannot see where the camshaft is in its rotation — no reliable camshaft position signal, or a circuit out of range. That is P0340. Some vehicles crank and will not start; others run poorly or stall when hot. Wiring at the connector, oil soaking the sensor, or a failed sensor are the usual suspects; timing belt or chain problems can also throw cam correlation off. Sorting signal loss from mechanical timing keeps you from replacing a sensor when the belt jumped.',
        'symptoms' => [
            'Check engine light with P0340 — may crank with no start on some models',
            'Stalling or hard restart when hot',
            'Rough running or reduced power',
            'Code after timing belt or chain service',
            'Oil leak soaking the cam sensor connector',
        ],
        'can_drive_heading' => 'Can I keep driving with a P0340 code?',
        'can_drive' => [
            'If it starts and runs, drive carefully to diagnosis — stalling risk is real on some vehicles.',
            'Crank no-start — do not keep cranking; tow or schedule mobile diagnosis.',
            'Stalling in traffic — treat as urgent.',
        ],
        'common_causes' => [
            'Failed camshaft position sensor',
            'Damaged wiring or connector at the sensor',
            'Oil contamination from a valve cover leak',
            'Timing belt or chain off one tooth (correlation codes may accompany)',
            'Aftermarket sensor with incorrect air gap',
        ],
        'often_confused_with' => [
            'P0016 crank/cam correlation — timing mechanical issue',
            'Crank sensor codes — different circuit, similar no-start',
        ],
        'if_you_ignore' => [
            'Stranded no-start',
            'Stalling in traffic',
            'Timing damage if the belt jumped and only the sensor is replaced',
        ],
        'repair_overview' => [
            'Oscilloscope or scan data for cam signal presence',
            'Inspect connector and oil intrusion',
            'Verify timing correlation when sensor and wiring look good',
        ],
        'what_happens_next' => [
            'Call with whether it is a no-start, a stall, or just the light on.',
            'We test the cam signal circuit and timing evidence before swapping the sensor.',
        ],
        'faq' => [
            [
                'question' => 'What does P0340 mean?',
                'answer' => 'P0340 is Camshaft Position Sensor Circuit Malfunction. The engine computer did not receive a valid cam position signal from the sensor circuit.',
            ],
            [
                'question' => 'Will P0340 prevent my car from starting?',
                'answer' => 'On some models, yes — crank no-start until the cam signal is restored. On others it runs rough or stalls. Tow in if it will not start reliably.',
            ],
        ],
        'related_problem_slugs' => ['check-engine-light', 'car-wont-start', 'honda-timing-belt'],
    ],
    [
        'slug' => 'p0135',
        'title' => 'P0135 Check Engine Code',
        'page_title' => 'P0135 Code: O2 Sensor Heater Circuit (Bank 1 Sensor 1)',
        'tier' => 2,
        'concern_prefill' => 'My check engine light is on with code P0135 — O2 sensor heater circuit bank 1 sensor 1.',
        'meta_description' => 'P0135 oxygen sensor heater code in Colorado Springs? Upstream O2 heater circuit fault explained — emissions and fuel trim effects, and how LugsNPlugs tests wiring before replacing sensors.',
        'problem' => 'The upstream oxygen sensor on bank 1 (sensor 1, before the catalytic converter) has a built-in heater that should warm it up fast so the computer can trim fuel and finish emissions monitors. When that heater circuit fails, you get P0135 — often with no change in how the car drives. Cold weather is when you notice it: longer rich warm-up, slow readiness, and a light that will not clear until the heater path (sensor, wiring, or fuse) is fixed.',
        'symptoms' => [
            'Check engine light with P0135 — often no obvious symptom',
            'Emissions monitors slow to become ready',
            'Slightly longer warm-up rich running in winter',
            'May appear with other O2 heater codes on high-mileage vehicles',
            'After exhaust or header work that disturbed sensor wiring',
        ],
        'can_drive_heading' => 'Can I keep driving with a P0135 code?',
        'can_drive' => [
            'Yes for daily driving in most cases — schedule repair before emissions testing.',
            'If multiple O2 codes and rich or lean faults appear, diagnose sooner — fuel economy may suffer.',
        ],
        'common_causes' => [
            'Failed upstream O2 sensor heater element',
            'Damaged wiring or fuse for the heater circuit',
            'Exhaust leak affecting the sensor — separate from heater but co-diagnosed',
            'Aftermarket sensor with incorrect spec',
        ],
        'often_confused_with' => [
            'P0134 no activity — sensor signal problem, not heater',
            'P0420 catalyst efficiency — downstream monitor, different sensor',
        ],
        'if_you_ignore' => [
            'Emissions readiness failure',
            'Gradual fuel economy loss in cold weather',
            'Heater codes spreading to other sensors',
        ],
        'repair_overview' => [
            'Test heater circuit resistance and fuse',
            'Inspect wiring near hot exhaust components',
            'Replace sensor when circuit and connector are proven good',
        ],
        'what_happens_next' => [
            'Mention any emissions deadline and recent exhaust work when you book.',
            'We test the heater circuit before quoting an upstream O2 sensor.',
        ],
        'faq' => [
            [
                'question' => 'What does P0135 mean?',
                'answer' => 'P0135 is O2 Sensor Heater Circuit Malfunction (Bank 1 Sensor 1). Bank 1 is the side of the engine that has cylinder 1. Sensor 1 is the upstream oxygen sensor before the catalytic converter. Its electric heater is not operating within spec.',
            ],
            [
                'question' => 'Do I need to fix P0135 right away?',
                'answer' => 'Daily driving is usually fine, but emissions monitors may not complete until the heater is fixed — plan ahead if registration or testing is coming up.',
            ],
        ],
        'related_problem_slugs' => ['p0420', 'check-engine-light'],
    ],
    [
        'slug' => 'p0016',
        'title' => 'P0016 Check Engine Code',
        'page_title' => 'P0016 Code: Crank / Cam Position Correlation',
        'tier' => 2,
        'concern_prefill' => 'My check engine light is on with code P0016 — crankshaft camshaft position correlation bank 1.',
        'meta_description' => 'P0016 timing correlation code in Colorado Springs? Cam and crank out of sync explained — timing chain, belt, or sensor causes. When to stop driving and how LugsNPlugs verifies timing before major engine work.',
        'problem' => 'Valve timing is not lining up with piston position the way the computer expects — crankshaft and camshaft position signals are out of sync. That correlation fault is P0016. On high-mileage chain engines, stretched chains or worn tensioners are common; on belt engines, a jumped tooth is serious. Some cases are only a bad sensor or wiring with no mechanical slip. Live cam/crank data and a timing check separate an expensive chain or belt job from a circuit repair before you open the front cover.',
        'symptoms' => [
            'Check engine light with P0016 — may run rough, rattle on start, or lack power',
            'Rattle at cold start on chain-driven engines (VVT rattle)',
            'Code after timing belt or chain service',
            'Hard start or stall',
            'May appear with P0017 on bank 2',
        ],
        'can_drive_heading' => 'Can I keep driving with a P0016 code?',
        'can_drive' => [
            'If the engine runs smoothly, drive carefully to diagnosis — but do not put off timing correlation codes.',
            'Loud rattle on start, rough running, or stall — minimize driving; timing slip can cause valve contact on interference engines.',
            'After timing service, do not drive until correlation is verified.',
        ],
        'common_causes' => [
            'Stretched timing chain or worn tensioner',
            'Jumped timing belt tooth',
            'Failed VVT solenoid or actuator (when chain is still in spec)',
            'Cam or crank sensor wiring fault mimicking a correlation error',
            'Incorrect timing after water pump or belt job',
        ],
        'often_confused_with' => [
            'P0340 cam sensor circuit — signal loss vs. correlation',
            'P0017 bank 2 correlation — opposite bank',
        ],
        'if_you_ignore' => [
            'Valve and piston contact on interference engines if timing jumps further',
            'Chain failure on startup',
            'Expensive head work from deferred timing correction',
        ],
        'repair_overview' => [
            'Read cam/crank correlation with a scan tool at idle and off idle',
            'Inspect chain rattle, belt marks, or VVT operation',
            'Verify sensor signals before condemning mechanical timing',
        ],
        'what_happens_next' => [
            'Call with any cold-start rattle, recent timing service, and mileage.',
            'We verify cam/crank correlation and mechanical timing before quoting chain, belt, or sensor work.',
        ],
        'faq' => [
            [
                'question' => 'What does P0016 mean?',
                'answer' => 'P0016 is Crankshaft Position Camshaft Position Correlation Bank 1. Bank 1 is the side of the engine that has cylinder 1. The computer compared crank and cam signals and found they do not align — mechanical timing slip or a sensor/circuit issue.',
            ],
            [
                'question' => 'Is P0016 always a timing chain?',
                'answer' => 'Often on high-mileage chain engines, but not always. We check sensors, VVT solenoids, and wiring before quoting major timing work.',
            ],
            [
                'question' => 'Can I keep driving with P0016?',
                'answer' => 'If it runs smoothly, come in soon — do not put it off. Loud rattle on start, rough running, or stalling means minimize driving until timing is verified.',
            ],
        ],
        'related_problem_slugs' => ['check-engine-light', 'honda-timing-belt', 'rough-idle'],
    ],
];
