<?php

$lnpTenantProfile = [
    'tables' => [
        'customers' => 'users',
        'vehicles' => 'vehicles',
        'repair_orders' => 'repair_orders',
        'concerns' => 'repair_order_concerns',
        'lines' => 'repair_order_line_items',
        'invoices' => 'invoices',
        'repair_order_statuses' => 'repair_order_statuses',
        'repair_order_status_logs' => 'repair_order_status_logs',
    ],
    'columns' => [
        'customers' => [
            'id' => 'id',
            'first_name' => 'first_name',
            'last_name' => 'last_name',
            'phone' => 'phone',
            'email' => 'email',
            'customer_type' => 'customer_type',
            'notes' => 'commercial_notes',
        ],
        'vehicles' => [
            'id' => 'id',
            'customer_id' => 'customer_id',
            'vin' => 'vehicle_vin',
            'plate' => 'vehicle_plate',
            'plate_state' => 'vehicle_state',
            'year' => 'vehicle_year',
            'make' => 'vehicle_make',
            'model' => 'vehicle_model',
            'trim' => 'vehicle_trim',
            'engine' => 'vehicle_engine',
            'transmission' => 'vehicle_transmission',
            'drive' => 'vehicle_drive',
            'color' => 'vehicle_color',
            'nickname' => 'vehicle_nickname',
            'public_notes' => 'vehicle_public_notes',
            'private_notes' => 'vehicle_private_notes',
        ],
        'repair_orders' => [
            'id' => 'id',
            'shop_number' => 'repair_order_id',
            'customer_id' => 'customer_id',
            'vehicle_id' => 'vehicle_id',
            'status' => 'status_slug',
            'concern_summary' => 'customer_complaint',
            'mileage_in' => 'mileage_in',
            'mileage_out' => 'mileage_out',
            'notes' => 'private_notes',
            'paid_at' => 'invoice_paid_at',
            'opened_at' => 'created_at',
            'status_changed_at' => 'status_changed_at',
        ],
        'concerns' => [
            'id' => 'id',
            'repair_order_id' => 'repair_order_id',
            'summary' => 'title',
            'notes' => 'customer_complaint',
            'disposition' => 'concern_status',
            'position' => 'sort_order',
            'deleted_at' => 'deleted_at',
        ],
        'lines' => [
            'id' => 'id',
            'repair_order_id' => 'repair_order_id',
            'concern_id' => 'repair_order_concern_id',
            'type' => 'type',
            'description' => 'description',
            'quantity' => 'quantity',
            'unit_price' => 'unit_price',
            'part_cost' => 'unit_cost',
            'subtotal' => 'computed_subtotal',
            'tax' => 'tax_amount',
            'shop_fee' => 'shop_fee_amount',
            'total' => 'line_total',
            'deleted_at' => 'deleted_at',
        ],
        'invoices' => [
            'id' => 'id',
            'repair_order_id' => 'repair_order_id',
            'invoice_number' => 'invoice_number',
            'subtotal' => 'subtotal',
            'tax' => 'tax_total',
            'shop_fee' => 'shop_fees_total',
            'total' => 'total',
            'generated_at' => 'finalized_at',
            'paid_at' => 'paid_at',
        ],
    ],
    'customer_scope' => 'vehicle_or_ro_customers',
];

return [

    'connection' => env('ARKSMS_LEGACY_CONNECTION', 'arksms_legacy'),

    'profile' => env('ARKSMS_LEGACY_PROFILE', 'default'),

    'profiles' => [
        'default' => [
            'tables' => [
                'customers' => env('ARKSMS_LEGACY_TABLE_CUSTOMERS', 'customers'),
                'vehicles' => env('ARKSMS_LEGACY_TABLE_VEHICLES', 'vehicles'),
                'repair_orders' => env('ARKSMS_LEGACY_TABLE_REPAIR_ORDERS', 'repair_orders'),
                'concerns' => env('ARKSMS_LEGACY_TABLE_CONCERNS', 'repair_order_concerns'),
                'lines' => env('ARKSMS_LEGACY_TABLE_LINES', 'repair_order_lines'),
                'invoices' => env('ARKSMS_LEGACY_TABLE_INVOICES', 'invoices'),
            ],
            'columns' => [
                'customers' => [
                    'id' => 'id',
                    'first_name' => 'first_name',
                    'last_name' => 'last_name',
                    'phone' => 'phone',
                    'email' => 'email',
                    'customer_type' => 'customer_type',
                    'notes' => 'notes',
                    'deleted_at' => 'deleted_at',
                ],
                'vehicles' => [
                    'id' => 'id',
                    'customer_id' => 'customer_id',
                    'vin' => 'vin',
                    'plate' => 'license_plate',
                    'plate_state' => 'license_plate_state',
                    'year' => 'year',
                    'make' => 'make',
                    'model' => 'model',
                    'trim' => 'trim',
                    'engine' => 'engine',
                    'transmission' => 'transmission',
                    'drive' => 'drivetrain',
                    'color' => 'color',
                    'nickname' => 'nickname',
                    'public_notes' => 'notes',
                    'private_notes' => 'private_notes',
                    'mileage' => 'mileage',
                    'deleted_at' => 'deleted_at',
                ],
                'repair_orders' => [
                    'id' => 'id',
                    'customer_id' => 'customer_id',
                    'vehicle_id' => 'vehicle_id',
                    'status' => 'status',
                    'concern_summary' => 'concern_summary',
                    'mileage_in' => 'mileage_in',
                    'mileage_out' => 'mileage_out',
                    'notes' => 'notes',
                    'payment_status' => 'payment_status',
                    'paid_at' => 'paid_at',
                    'opened_at' => 'created_at',
                    'status_changed_at' => 'status_changed_at',
                    'deleted_at' => 'deleted_at',
                ],
                'concerns' => [
                    'id' => 'id',
                    'repair_order_id' => 'repair_order_id',
                    'summary' => 'summary',
                    'notes' => 'notes',
                    'disposition' => 'disposition',
                    'position' => 'position',
                ],
                'lines' => [
                    'id' => 'id',
                    'repair_order_id' => 'repair_order_id',
                    'concern_id' => 'repair_order_concern_id',
                    'type' => 'type',
                    'description' => 'description',
                    'quantity' => 'quantity',
                    'unit_price' => 'unit_price',
                    'part_cost' => 'part_cost',
                    'subtotal' => 'subtotal',
                    'tax' => 'tax',
                    'shop_fee' => 'shop_fee',
                    'total' => 'total',
                    'vendor_name' => 'vendor_name',
                    'part_number' => 'part_number',
                ],
                'invoices' => [
                    'id' => 'id',
                    'repair_order_id' => 'repair_order_id',
                    'invoice_number' => 'invoice_number',
                    'subtotal' => 'subtotal',
                    'tax' => 'tax',
                    'shop_fee' => 'shop_fee',
                    'total' => 'total',
                    'generated_at' => 'created_at',
                ],
            ],
        ],
        'lnp_tenant' => $lnpTenantProfile,
    ],

    'status_map' => [
        'draft' => 'draft',
        'new' => 'draft',
        'intake' => 'draft',
        'estimate' => 'estimate',
        'estimating' => 'estimate',
        'diagnosis' => 'estimate',
        'waiting_approval' => 'waiting_approval',
        'awaiting_approval' => 'waiting_approval',
        'pending_approval' => 'waiting_approval',
        'approved' => 'approved',
        'waiting_parts' => 'waiting_parts',
        'parts' => 'waiting_parts',
        'ready_for_work' => 'ready_for_work',
        'scheduled' => 'ready_for_work',
        'in_progress' => 'in_progress',
        'in_shop' => 'in_progress',
        'working' => 'in_progress',
        'quality_check' => 'quality_check',
        'ready_pickup' => 'ready_pickup',
        'ready' => 'ready_pickup',
        'complete' => 'completed',
        'completed' => 'completed',
        'closed' => 'closed',
        'invoiced' => 'invoiced',
        'paid' => 'invoiced',
        'archived' => 'closed',
        'cancelled' => 'closed',
        'void' => 'closed',
    ],

    'report_path' => 'imports/ark-sms/latest-import-report.json',

    'checkpoint_path' => 'imports/ark-sms/checkpoint.json',

];
